interface CloudflareEnv {
  BETTER_AUTH_URL?: string;
  BETTER_AUTH_SECRET: string;
  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;
  ALIYUN_ACCESS_KEY_ID?: string;
  ALIYUN_ACCESS_KEY_SECRET?: string;
  ALIYUN_DIRECTMAIL_ACCOUNT_NAME?: string;
  ALIYUN_DIRECTMAIL_FROM_ALIAS?: string;
  ALIYUN_DIRECTMAIL_REGION_ID?: string;
  ALIYUN_DIRECTMAIL_ENDPOINT?: string;
  REDEEM_CODE_PEPPER?: string;
  AGENT_ACCESS_TOKEN_PEPPER?: string;
}
